string[] serials         # serial numbers to select specific cameras (emtpy array means all cameras)
---
bool success             # indicate successful run of triggered service
string message           # informational, e.g. for error messages
